export type Env = {
  DB: DatabaseLike;
  BROWSER?: unknown;
  IV_DOMAIN?: string;
  IV_AUTH?: string;
};

export type DatabaseLike = any;

export type CacheData = {
  response: string;
  headers: {
    'Content-Type': string;
    'Cached-On': string;
  };
};

export type CacheDataEntry = {
  Entry: string;
  Expiration: number;
};

type ThumbnailObject = { url: string; width: number; height: number };
type FormatStream = {
  url: string;
  itag: string;
  type: string;
  quality: string;
  container: string;
  encoding: string;
  qualityLabel: string;
  resolution: string;
  size: string;
};

export type Video = {
  title: string; type?: string; error?: string; videoThumbnails: ThumbnailObject[];
  description: string; publishedText: string; viewCount: number; likeCount: number;
  dislikeCount: number; author: string; authorUrl: string; authorId: string;
  authorThumbnails?: ThumbnailObject[]; subCountText: string; isListed: boolean;
  liveNow: boolean; isUpcoming: boolean; formatStreams: FormatStream[];
  isAuthorVerified: boolean;
};
export type RYDResponse = { id: string; dateCreated: string; likes: number; dislikes: number; rating: number; viewCount: number; deleted: boolean };
export type DeArrowResponse = { titles: any[]; thumbnails: any[]; randomTime: number; videoDuration: number | null };
export type ResolvedURL = { ucid?: string; videoId?: string; playlistId?: string; startTimeSeconds?: string; params?: string; pageType: string };
export type PlaylistInfo = { title: string; playlistThumbnail: string; description: string; author: string; authorUrl: string; authorId: string; videoCount: number; viewCount: number; updated: number; videos: any[]; error?: string };
export type ChannelInfo = { author: string; authorId: string; authorUrl: string; authorBanners: ThumbnailObject[]; authorThumbnails: ThumbnailObject[]; subCount: number; totalViews: number; joined: number; autoGenerated: boolean; isFamilyFriendly: boolean; description: string; descriptionHtml: string; allowedRegions: string[]; tabs: string[]; authorVerified: boolean; latestVideos: Video[]; relatedChannels: unknown[]; error?: string };
export type PublicCacheEntry = { url: string; type: string; timecode?: string; expiration?: number; size: string | null; itag: string | null; dearrow: string | null; stock: string | null };
export type VideoEmbedData = any;
export type PlaylistEmbedData = any;
export type ChannelEmbedData = any;
export type MixInfo = any;
export type MixEmbedData = any;
